name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
          provenance: true
          labels: |
              org.opencontainers.image.source=${{ github.repository }}
              org.opencontainers.image.revision=${{ github.sha }}
              org.opencontainers.image.authors=${{ github.actor }}
              org.opencontainers.image.url=https://github.com/${{ github.repository }}
          sbom: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Redeploy via webhook
        env:
          REDEPLOY_WEBHOOK: ${{ secrets.REDEPLOY_WEBHOOK }}
        run: |
          if [ -n "$REDEPLOY_WEBHOOK" ]; then
            curl -X POST "$REDEPLOY_WEBHOOK"
            echo "Redeploy webhook triggered successfully."
            exit 0
          else
            echo "No redeploy webhook set."
            exit 1
          fi
